<?php

// autoload.php @generated by Composer

// Custom error handler to suppress GuzzleHttp Promises deprecation warnings
set_error_handler(function ($severity, $message, $file, $line) {
    // Suppress deprecation warnings from GuzzleHttp vendor directory
    if ($severity === E_DEPRECATED &&
        (strpos($file, 'vendor/guzzlehttp/promises') !== false ||
         strpos($file, 'vendor\\guzzlehttp\\promises') !== false) &&
        (strpos($message, 'Implicitly marking parameter') !== false &&
         strpos($message, 'as nullable is deprecated') !== false)) {
        return true; // Don't execute the internal error handler
    }

    // For all other errors, use the default error handler
    return false;
});

if (PHP_VERSION_ID < 50600) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, $err);
        } elseif (!headers_sent()) {
            echo $err;
        }
    }
    throw new RuntimeException($err);
}

require_once __DIR__ . '/vendor/composer/autoload_real.php';

return ComposerAutoloaderInita9cfa8b5d1d5a587bb5e2355faa68ea6::getLoader();
